import { test } from 'node:test'
import assert from 'node:assert/strict'
import JSZip from 'jszip'
import { docx, preflight } from '../dist/documents.esm.js'
import { acmeKit, neutralKit, PNG_1x1, wordmarkKit, paleTenantKit, inkTenantKit, unusualFontKit } from './fixtures.mjs'

const EMU_PER_PX = 9525

/** A representative base document: masthead, headings, kv table, data table. */
async function goldenDoc(kit, withLogo, logoWidthPx = 200) {
  const doc = docx.createDocument(kit, {
    title: 'Prestart Briefing',
    sections: [
      {
        children: [
          docx.masthead(kit, { title: 'Prestart Briefing', subtitle: 'Site: Example Rd', logoBytes: withLogo ? PNG_1x1 : undefined, logoWidthPx }),
          docx.h1('Details'),
          docx.kvTable(kit, [
            ['Date', '23 Sep 2026'],
            ['Supervisor', 'A. Person'],
          ]),
          docx.h2('Attendees'),
          docx.dataTable(kit, { head: ['Name', 'Role', 'Signed'], rows: [['A', 'Lead', 'Yes'], ['B', 'Crew', 'Yes'], ['C', 'Crew', 'No']] }),
          docx.body('All hazards discussed.'),
          docx.small('Generated by EQ.'),
        ],
      },
    ],
  })
  return docx.toUint8Array(doc)
}

test('golden: acme document has named styles, kit colours only, kit fonts only, legal footer', async () => {
  const bytes = await goldenDoc(acmeKit, true)
  const zip = await JSZip.loadAsync(bytes)
  const styles = await zip.file('word/styles.xml').async('string')
  for (const id of docx.DOC_STYLE_IDS) assert.ok(styles.includes(`w:styleId="${id}"`), `style ${id} present`)
  const document = await zip.file('word/document.xml').async('string')
  assert.ok(document.includes('w:val="DocTitle"'))
  assert.ok(document.includes('w:val="DocTableHead"'))

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [acmeKit.logos.light.url] })
  assert.equal(result.ok, true, result.line)
  assert.ok(result.line.startsWith('Brand check: ✓ logo ✓ ratio ✓ palette ✓ fonts ✓ flat ✓ footer'))
  assert.ok(facts.footerText.includes('Acme Pty Ltd'))
  assert.ok(facts.footerText.includes('ABN 11 111 111 111'))
  assert.deepEqual([...facts.usedFonts].sort(), ['Calibri', 'Roboto'])
})

test('golden: logo placed at stored aspect ratio (2000×723) regardless of the image bytes', async () => {
  const bytes = await goldenDoc(acmeKit, true)
  const facts = await preflight.extractFacts(bytes)
  assert.equal(facts.logoPlacements.length, 1)
  const [p] = facts.logoPlacements
  assert.ok(Math.abs(p.width / p.height - 2000 / 723) < 0.02, `ratio ${p.width / p.height}`)
})

test('golden: neutral kit renders grey, no logo, still passes preflight', async () => {
  const bytes = await goldenDoc(neutralKit, false)
  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(neutralKit, facts)
  assert.equal(result.ok, true, result.line)
  assert.equal(facts.logoPlacements.length, 0)
  for (const hex of facts.usedHex) assert.notEqual(hex, '3DA8D8', 'no EQ brand in a neutral document')
})

test('preflight catches a foreign colour, a stretched logo, a foreign font and a wrong footer', () => {
  const r = preflight.preflight(acmeKit, {
    usedHex: ['1F4E79', '3DA8D8'],
    usedFonts: ['Calibri', 'Plus Jakarta Sans'],
    hasEffects: true,
    hasFooter: true,
    footerText: 'Other Company Pty Ltd',
    logoSources: ['https://elsewhere.test/logo.png'],
    logoPlacements: [{ width: 200, height: 200 }],
  })
  assert.equal(r.ok, false)
  assert.deepEqual(r.checks.map((c) => c.pass), [false, false, false, false, false, false])
  assert.ok(r.line.includes('✗ palette → colours outside kit: 3DA8D8'))
  assert.ok(r.line.includes('✗ fonts → fonts outside kit: Plus Jakarta Sans'))
})

test('preflight grades the header text colour textOn() actually picked, not an assumed white', () => {
  // A light primary (EQ's real sky blue) fails contrast with white (2.70:1)
  // but passes easily with a dark ink (6.33:1) — headCell() calls
  // textOn(primary, ink) and gets ink, so the rendered header is never
  // actually white. The palette check must grade that real choice.
  const lightPrimaryKit = {
    ...acmeKit,
    palette: { primary: '3DA8D8', deep: '2986B4', ice: 'EAF5FB', ink: '1A1A2E' },
  }
  const r = preflight.preflight(lightPrimaryKit, {
    usedHex: ['3DA8D8', '2986B4', 'EAF5FB', '1A1A2E', 'FFFFFF', 'AUTO'],
    usedFonts: [acmeKit.fonts.heading, acmeKit.fonts.body, acmeKit.fonts.docBody],
    hasEffects: false,
    hasFooter: true,
    footerText: acmeKit.tenant.legalName,
    logoSources: [],
    logoPlacements: [],
  })
  const palette = r.checks.find((c) => c.id === 'palette')
  assert.equal(palette.pass, true, palette.detail)
})

test('footer pageNumbers option emits PAGE/NUMPAGES fields and still passes preflight', async () => {
  const doc = docx.createDocument(acmeKit, {
    title: 'Prestart Briefing',
    pageNumbers: true,
    sections: [{ children: [docx.h1('Details'), docx.body('x')] }],
  })
  const bytes = await docx.toUint8Array(doc)
  const zip = await JSZip.loadAsync(bytes)
  const footerFiles = Object.keys(zip.files).filter((n) => /^word\/footer\d*\.xml$/.test(n))
  assert.ok(footerFiles.length > 0, 'a footer part exists')
  const footerXml = await zip.file(footerFiles[0]).async('string')
  assert.ok(footerXml.includes('PAGE'), 'footer carries a PAGE field')
  assert.ok(footerXml.includes('NUMPAGES'), 'footer carries a NUMPAGES field')

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [] })
  assert.equal(result.ok, true, result.line)
  assert.ok(facts.footerText.includes(acmeKit.tenant.legalName))
})

test('footer omits page-number fields by default', async () => {
  const doc = docx.createDocument(acmeKit, { sections: [{ children: [docx.body('x')] }] })
  const bytes = await docx.toUint8Array(doc)
  const zip = await JSZip.loadAsync(bytes)
  const footerFiles = Object.keys(zip.files).filter((n) => /^word\/footer\d*\.xml$/.test(n))
  const footerXml = await zip.file(footerFiles[0]).async('string')
  assert.ok(!footerXml.includes('NUMPAGES'), 'no page-number field unless opted in')
})

test('toBlob works where Blob exists (browser path)', async () => {
  const doc = docx.createDocument(acmeKit, { sections: [{ children: [docx.body('x')] }] })
  const blob = await docx.toBlob(doc)
  assert.ok(blob.size > 1000)
})

test('signatureGrid + photoGrid render alongside a logo, and preflight grades only the logo\'s ratio', async () => {
  const sigTable = docx.signatureGrid(acmeKit, {
    attendees: [
      { name: 'A. Person', sig: { bytes: PNG_1x1, mime: 'image/png' } },
      { name: 'B. Person' }, // unsigned — blank ice cell, no image
    ],
  })
  const photos = docx.photoGrid(acmeKit, {
    photos: [
      { bytes: PNG_1x1, mime: 'image/png', caption: 'Before' },
      { bytes: PNG_1x1, mime: 'image/png', caption: 'After' },
    ],
  })
  const doc = docx.createDocument(acmeKit, {
    sections: [
      {
        children: [
          docx.masthead(acmeKit, { title: 'Toolbox', logoBytes: PNG_1x1, logoWidthPx: 200 }),
          docx.h2('Signatures'),
          sigTable,
          docx.h2('Photos'),
          photos,
        ],
      },
    ],
  })
  const bytes = await docx.toUint8Array(doc)

  const facts = await preflight.extractFacts(bytes)
  // 1 logo (200×72.3, kept at the kit's 2000×723 ratio) + 1 signature (144×48) + 2 photos (288×216)
  // = 4 images placed, but only the logo should ever reach logoPlacements.
  assert.equal(facts.logoPlacements.length, 1, 'signature/photo images must not be graded as the logo')
  const [p] = facts.logoPlacements
  assert.ok(Math.abs(p.width / p.height - 2000 / 723) < 0.02, `logo ratio ${p.width / p.height}`)

  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [acmeKit.logos.light.url] })
  assert.equal(result.ok, true, result.line)
})


test('guard 1 — masthead width guard clamps a wordmark logo to the logo column budget, preserving its aspect ratio', async () => {
  // Requested at 400px — comfortably wider than the ~185px logo-column
  // budget a wordmark tenant is likely to ask for (a wide logo looks tiny,
  // and therefore illegible, at the 180px default).
  const requestedWidthPx = 400
  const bytes = await goldenDoc(wordmarkKit, true, requestedWidthPx)
  const facts = await preflight.extractFacts(bytes)
  assert.equal(facts.logoPlacements.length, 1)
  const [p] = facts.logoPlacements

  // Guard fired: the placed width is smaller than the naive/requested one.
  assert.ok(p.width < requestedWidthPx * EMU_PER_PX, `expected clamp, got ${p.width} EMU (requested ${requestedWidthPx * EMU_PER_PX})`)
  // Aspect ratio (3000×400) is still preserved — the guard scales, never crops or stretches.
  // Relative tolerance (not the other tests' absolute 0.02) — a wordmark's 7.5:1 ratio at a
  // ~185px width rounds height to the nearest px, which moves the ratio more in absolute terms
  // than the other fixtures' ~2.7:1 logos do at their larger placed sizes.
  const ratio = p.width / p.height
  assert.ok(Math.abs(ratio - 3000 / 400) / (3000 / 400) < 0.02, `ratio ${ratio}`)

  const result = preflight.preflight(wordmarkKit, { ...facts, logoSources: [wordmarkKit.logos.light.url] })
  assert.equal(result.ok, true, result.line)
})

test('guard 1 — a logo already inside the column budget (the 180px default) is left untouched', async () => {
  const doc = docx.createDocument(acmeKit, {
    sections: [{ children: [docx.masthead(acmeKit, { title: 'Prestart Briefing', logoBytes: PNG_1x1 })] }], // logoWidthPx omitted — exercises the 180px default
  })
  const bytes = await docx.toUint8Array(doc)
  const facts = await preflight.extractFacts(bytes)
  const [p] = facts.logoPlacements
  assert.equal(p.width, Math.round(180 * EMU_PER_PX), 'default width renders unclamped')
})

test('guard 2 — header-fill intensity guard falls back to palette.deep for a near-white primary, and stays readable', async () => {
  const bytes = await goldenDoc(paleTenantKit, false)
  const zip = await JSZip.loadAsync(bytes)
  const document = await zip.file('word/document.xml').async('string')
  assert.ok(document.includes(`w:fill="${paleTenantKit.palette.deep}"`), 'header row fills with palette.deep')
  assert.ok(!document.includes(`w:fill="${paleTenantKit.palette.primary}"`), 'the near-white primary is never used as a fill')

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(paleTenantKit, { ...facts, logoSources: [] })
  assert.equal(result.ok, true, result.line)
})

test('guard 2 — header-fill intensity guard falls back to palette.deep for a near-black primary', async () => {
  const bytes = await goldenDoc(inkTenantKit, false)
  const zip = await JSZip.loadAsync(bytes)
  const document = await zip.file('word/document.xml').async('string')
  assert.ok(document.includes(`w:fill="${inkTenantKit.palette.deep}"`), 'header row fills with palette.deep')
  assert.ok(!document.includes(`w:fill="${inkTenantKit.palette.primary}"`), 'the near-black primary is never used as a fill')

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(inkTenantKit, { ...facts, logoSources: [] })
  assert.equal(result.ok, true, result.line)
})

test('guard 2 — a normal mid-tone primary (acme) still fills the header directly, unaffected by the guard', async () => {
  assert.equal(docx.tableHeadFill(acmeKit), acmeKit.palette.primary)
})

test('guard 3 — font fallback safety net pins eastAsia/cs to Arial for an unrecognised heading font, without replacing it', async () => {
  const bytes = await goldenDoc(unusualFontKit, false)
  const zip = await JSZip.loadAsync(bytes)
  const styles = await zip.file('word/styles.xml').async('string')
  assert.ok(styles.includes('w:ascii="Brush Script MT"'), 'the tenant\'s requested font is still used, not rejected')
  assert.ok(styles.includes('w:eastAsia="Arial"') && styles.includes('w:cs="Arial"'), 'unsupported font gets an Arial safety net on eastAsia/cs')

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(unusualFontKit, { ...facts, logoSources: [] })
  assert.equal(result.ok, true, result.line)
})

test('guard 3 — a safe font (acme\'s Roboto/Calibri) never gets the Arial fallback substituted in', async () => {
  const bytes = await goldenDoc(acmeKit, false)
  const zip = await JSZip.loadAsync(bytes)
  const styles = await zip.file('word/styles.xml').async('string')
  // docx's createRunFonts always expands a plain string into all four rFonts
  // faces (ascii/hAnsi/eastAsia/cs) — a safe font shows the SAME name on all
  // of them, never a divergent Arial fallback the way unusualFontKit does.
  assert.ok(!styles.includes('w:eastAsia="Arial"'), 'no Arial fallback substituted for a font already on the safe list')
  assert.ok(styles.includes('w:eastAsia="Roboto"'), 'heading font faces all agree — no fallback split')
})

test('alertTable keeps its fixed amber regardless of tenant kit, and preflight allows it', async () => {
  const alertTable = docx.alertTable({ lines: ['HIGH-RISK CONSTRUCTION WORK — WHS Reg Sch 3'] })
  const doc = docx.createDocument(acmeKit, {
    sections: [{ children: [docx.h1('Prestart'), alertTable, docx.dataTable(acmeKit, { head: ['Name'], rows: [['A']] })] }],
  })
  const bytes = await docx.toUint8Array(doc)
  const facts = await preflight.extractFacts(bytes)

  assert.ok(facts.usedHex.map((h) => h.toUpperCase()).includes(docx.ALERT_AMBER), 'alert amber should appear in the rendered document')

  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [] })
  assert.equal(result.ok, true, result.line)

  // Same amber for a completely different tenant kit — it's not palette-derived.
  const neutralAlertTable = docx.alertTable({ lines: ['HIGH-RISK CONSTRUCTION WORK'] })
  const neutralDoc = docx.createDocument(neutralKit, { sections: [{ children: [neutralAlertTable] }] })
  const neutralBytes = await docx.toUint8Array(neutralDoc)
  const neutralFacts = await preflight.extractFacts(neutralBytes)
  assert.ok(neutralFacts.usedHex.map((h) => h.toUpperCase()).includes(docx.ALERT_AMBER), 'amber is fixed, not kit.palette-derived')
  assert.equal(preflight.preflight(neutralKit, { ...neutralFacts, logoSources: [] }).ok, true)
})
