import { test } from 'node:test'
import assert from 'node:assert/strict'
import JSZip from 'jszip'
import { docx, preflight } from '../dist/documents.esm.js'
import { acmeKit, neutralKit, PNG_1x1 } from './fixtures.mjs'

/** A representative base document: masthead, headings, kv table, data table. */
async function goldenDoc(kit, withLogo) {
  const doc = docx.createDocument(kit, {
    title: 'Prestart Briefing',
    sections: [
      {
        children: [
          docx.masthead(kit, { title: 'Prestart Briefing', subtitle: 'Site: Example Rd', logoBytes: withLogo ? PNG_1x1 : undefined, logoWidthPx: 200 }),
          docx.h1('Details'),
          docx.kvTable(kit, [
            ['Date', '23 Sep 2026'],
            ['Supervisor', 'A. Person'],
          ]),
          docx.h2('Attendees'),
          docx.dataTable(kit, { head: ['Name', 'Role', 'Signed'], rows: [['A', 'Lead', 'Yes'], ['B', 'Crew', 'Yes'], ['C', 'Crew', 'No']] }),
          docx.body('All hazards discussed.'),
          docx.small('Generated by EQ.'),
        ],
      },
    ],
  })
  return docx.toUint8Array(doc)
}

test('golden: acme document has named styles, kit colours only, kit fonts only, legal footer', async () => {
  const bytes = await goldenDoc(acmeKit, true)
  const zip = await JSZip.loadAsync(bytes)
  const styles = await zip.file('word/styles.xml').async('string')
  for (const id of docx.DOC_STYLE_IDS) assert.ok(styles.includes(`w:styleId="${id}"`), `style ${id} present`)
  const document = await zip.file('word/document.xml').async('string')
  assert.ok(document.includes('w:val="DocTitle"'))
  assert.ok(document.includes('w:val="DocTableHead"'))

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [acmeKit.logos.light.url] })
  assert.equal(result.ok, true, result.line)
  assert.ok(result.line.startsWith('Brand check: ✓ logo ✓ ratio ✓ palette ✓ fonts ✓ flat ✓ footer'))
  assert.ok(facts.footerText.includes('Acme Pty Ltd'))
  assert.ok(facts.footerText.includes('ABN 11 111 111 111'))
  assert.deepEqual([...facts.usedFonts].sort(), ['Calibri', 'Roboto'])
})

test('golden: logo placed at stored aspect ratio (2000×723) regardless of the image bytes', async () => {
  const bytes = await goldenDoc(acmeKit, true)
  const facts = await preflight.extractFacts(bytes)
  assert.equal(facts.logoPlacements.length, 1)
  const [p] = facts.logoPlacements
  assert.ok(Math.abs(p.width / p.height - 2000 / 723) < 0.02, `ratio ${p.width / p.height}`)
})

test('golden: neutral kit renders grey, no logo, still passes preflight', async () => {
  const bytes = await goldenDoc(neutralKit, false)
  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(neutralKit, facts)
  assert.equal(result.ok, true, result.line)
  assert.equal(facts.logoPlacements.length, 0)
  for (const hex of facts.usedHex) assert.notEqual(hex, '3DA8D8', 'no EQ brand in a neutral document')
})

test('preflight catches a foreign colour, a stretched logo, a foreign font and a wrong footer', () => {
  const r = preflight.preflight(acmeKit, {
    usedHex: ['1F4E79', '3DA8D8'],
    usedFonts: ['Calibri', 'Plus Jakarta Sans'],
    hasEffects: true,
    hasFooter: true,
    footerText: 'Other Company Pty Ltd',
    logoSources: ['https://elsewhere.test/logo.png'],
    logoPlacements: [{ width: 200, height: 200 }],
  })
  assert.equal(r.ok, false)
  assert.deepEqual(r.checks.map((c) => c.pass), [false, false, false, false, false, false])
  assert.ok(r.line.includes('✗ palette → colours outside kit: 3DA8D8'))
  assert.ok(r.line.includes('✗ fonts → fonts outside kit: Plus Jakarta Sans'))
})

test('preflight grades the header text colour textOn() actually picked, not an assumed white', () => {
  // A light primary (EQ's real sky blue) fails contrast with white (2.70:1)
  // but passes easily with a dark ink (6.33:1) — headCell() calls
  // textOn(primary, ink) and gets ink, so the rendered header is never
  // actually white. The palette check must grade that real choice.
  const lightPrimaryKit = {
    ...acmeKit,
    palette: { primary: '3DA8D8', deep: '2986B4', ice: 'EAF5FB', ink: '1A1A2E' },
  }
  const r = preflight.preflight(lightPrimaryKit, {
    usedHex: ['3DA8D8', '2986B4', 'EAF5FB', '1A1A2E', 'FFFFFF', 'AUTO'],
    usedFonts: [acmeKit.fonts.heading, acmeKit.fonts.body, acmeKit.fonts.docBody],
    hasEffects: false,
    hasFooter: true,
    footerText: acmeKit.tenant.legalName,
    logoSources: [],
    logoPlacements: [],
  })
  const palette = r.checks.find((c) => c.id === 'palette')
  assert.equal(palette.pass, true, palette.detail)
})

test('footer pageNumbers option emits PAGE/NUMPAGES fields and still passes preflight', async () => {
  const doc = docx.createDocument(acmeKit, {
    title: 'Prestart Briefing',
    pageNumbers: true,
    sections: [{ children: [docx.h1('Details'), docx.body('x')] }],
  })
  const bytes = await docx.toUint8Array(doc)
  const zip = await JSZip.loadAsync(bytes)
  const footerFiles = Object.keys(zip.files).filter((n) => /^word\/footer\d*\.xml$/.test(n))
  assert.ok(footerFiles.length > 0, 'a footer part exists')
  const footerXml = await zip.file(footerFiles[0]).async('string')
  assert.ok(footerXml.includes('PAGE'), 'footer carries a PAGE field')
  assert.ok(footerXml.includes('NUMPAGES'), 'footer carries a NUMPAGES field')

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [] })
  assert.equal(result.ok, true, result.line)
  assert.ok(facts.footerText.includes(acmeKit.tenant.legalName))
})

test('footer omits page-number fields by default', async () => {
  const doc = docx.createDocument(acmeKit, { sections: [{ children: [docx.body('x')] }] })
  const bytes = await docx.toUint8Array(doc)
  const zip = await JSZip.loadAsync(bytes)
  const footerFiles = Object.keys(zip.files).filter((n) => /^word\/footer\d*\.xml$/.test(n))
  const footerXml = await zip.file(footerFiles[0]).async('string')
  assert.ok(!footerXml.includes('NUMPAGES'), 'no page-number field unless opted in')
})

test('toBlob works where Blob exists (browser path)', async () => {
  const doc = docx.createDocument(acmeKit, { sections: [{ children: [docx.body('x')] }] })
  const blob = await docx.toBlob(doc)
  assert.ok(blob.size > 1000)
})

test('signatureGrid + photoGrid render alongside a logo, and preflight grades only the logo\'s ratio', async () => {
  const sigTable = docx.signatureGrid(acmeKit, {
    attendees: [
      { name: 'A. Person', sig: { bytes: PNG_1x1, mime: 'image/png' } },
      { name: 'B. Person' }, // unsigned — blank ice cell, no image
    ],
  })
  const photos = docx.photoGrid(acmeKit, {
    photos: [
      { bytes: PNG_1x1, mime: 'image/png', caption: 'Before' },
      { bytes: PNG_1x1, mime: 'image/png', caption: 'After' },
    ],
  })
  const doc = docx.createDocument(acmeKit, {
    sections: [
      {
        children: [
          docx.masthead(acmeKit, { title: 'Toolbox', logoBytes: PNG_1x1, logoWidthPx: 200 }),
          docx.h2('Signatures'),
          sigTable,
          docx.h2('Photos'),
          photos,
        ],
      },
    ],
  })
  const bytes = await docx.toUint8Array(doc)

  const facts = await preflight.extractFacts(bytes)
  // 1 logo (200×72.3, kept at the kit's 2000×723 ratio) + 1 signature (144×48) + 2 photos (288×216)
  // = 4 images placed, but only the logo should ever reach logoPlacements.
  assert.equal(facts.logoPlacements.length, 1, 'signature/photo images must not be graded as the logo')
  const [p] = facts.logoPlacements
  assert.ok(Math.abs(p.width / p.height - 2000 / 723) < 0.02, `logo ratio ${p.width / p.height}`)

  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [acmeKit.logos.light.url] })
  assert.equal(result.ok, true, result.line)
})
