import { test } from 'node:test'
import assert from 'node:assert/strict'
import JSZip from 'jszip'
import { docx, preflight } from '../dist/documents.esm.js'
import { acmeKit, neutralKit, PNG_1x1 } from './fixtures.mjs'

/** A representative base document: masthead, headings, kv table, data table. */
async function goldenDoc(kit, withLogo) {
  const doc = docx.createDocument(kit, {
    title: 'Prestart Briefing',
    sections: [
      {
        children: [
          docx.masthead(kit, { title: 'Prestart Briefing', subtitle: 'Site: Example Rd', logoBytes: withLogo ? PNG_1x1 : undefined, logoWidthPx: 200 }),
          docx.h1('Details'),
          docx.kvTable(kit, [
            ['Date', '23 Sep 2026'],
            ['Supervisor', 'A. Person'],
          ]),
          docx.h2('Attendees'),
          docx.dataTable(kit, { head: ['Name', 'Role', 'Signed'], rows: [['A', 'Lead', 'Yes'], ['B', 'Crew', 'Yes'], ['C', 'Crew', 'No']] }),
          docx.body('All hazards discussed.'),
          docx.small('Generated by EQ.'),
        ],
      },
    ],
  })
  return docx.toUint8Array(doc)
}

test('golden: acme document has named styles, kit colours only, kit fonts only, legal footer', async () => {
  const bytes = await goldenDoc(acmeKit, true)
  const zip = await JSZip.loadAsync(bytes)
  const styles = await zip.file('word/styles.xml').async('string')
  for (const id of docx.DOC_STYLE_IDS) assert.ok(styles.includes(`w:styleId="${id}"`), `style ${id} present`)
  const document = await zip.file('word/document.xml').async('string')
  assert.ok(document.includes('w:val="DocTitle"'))
  assert.ok(document.includes('w:val="DocTableHead"'))

  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(acmeKit, { ...facts, logoSources: [acmeKit.logos.light.url] })
  assert.equal(result.ok, true, result.line)
  assert.ok(result.line.startsWith('Brand check: ✓ logo ✓ ratio ✓ palette ✓ fonts ✓ flat ✓ footer'))
  assert.ok(facts.footerText.includes('Acme Pty Ltd'))
  assert.ok(facts.footerText.includes('ABN 11 111 111 111'))
  assert.deepEqual([...facts.usedFonts].sort(), ['Calibri', 'Roboto'])
})

test('golden: logo placed at stored aspect ratio (2000×723) regardless of the image bytes', async () => {
  const bytes = await goldenDoc(acmeKit, true)
  const facts = await preflight.extractFacts(bytes)
  assert.equal(facts.logoPlacements.length, 1)
  const [p] = facts.logoPlacements
  assert.ok(Math.abs(p.width / p.height - 2000 / 723) < 0.02, `ratio ${p.width / p.height}`)
})

test('golden: neutral kit renders grey, no logo, still passes preflight', async () => {
  const bytes = await goldenDoc(neutralKit, false)
  const facts = await preflight.extractFacts(bytes)
  const result = preflight.preflight(neutralKit, facts)
  assert.equal(result.ok, true, result.line)
  assert.equal(facts.logoPlacements.length, 0)
  for (const hex of facts.usedHex) assert.notEqual(hex, '3DA8D8', 'no EQ brand in a neutral document')
})

test('preflight catches a foreign colour, a stretched logo, a foreign font and a wrong footer', () => {
  const r = preflight.preflight(acmeKit, {
    usedHex: ['1F4E79', '3DA8D8'],
    usedFonts: ['Calibri', 'Plus Jakarta Sans'],
    hasEffects: true,
    hasFooter: true,
    footerText: 'Other Company Pty Ltd',
    logoSources: ['https://elsewhere.test/logo.png'],
    logoPlacements: [{ width: 200, height: 200 }],
  })
  assert.equal(r.ok, false)
  assert.deepEqual(r.checks.map((c) => c.pass), [false, false, false, false, false, false])
  assert.ok(r.line.includes('✗ palette → colours outside kit: 3DA8D8'))
  assert.ok(r.line.includes('✗ fonts → fonts outside kit: Plus Jakarta Sans'))
})

test('toBlob works where Blob exists (browser path)', async () => {
  const doc = docx.createDocument(acmeKit, { sections: [{ children: [docx.body('x')] }] })
  const blob = await docx.toBlob(doc)
  assert.ok(blob.size > 1000)
})
